spring:
  flyway:
    baseline-on-migrate: true
  application:
    name: Dern
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      validation-timeout: 3000
      pool-name: dern-hikari-pool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off
